/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 17:05:29 GMT 2024
 */

package com.iluwatar.visitor;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import com.iluwatar.visitor.Commander;
import com.iluwatar.visitor.Sergeant;
import com.iluwatar.visitor.Soldier;
import com.iluwatar.visitor.SoldierVisitor;
import com.iluwatar.visitor.Unit;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

 
public class SoldierVisitor_ESTest  {


  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      SoldierVisitor soldierVisitor0 = new SoldierVisitor();
      Unit[] unitArray0 = new Unit[2];
      Commander commander0 = new Commander(unitArray0);
      soldierVisitor0.visit(commander0);
      assertEquals("commander", commander0.toString());
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      SoldierVisitor soldierVisitor0 = new SoldierVisitor();
      Unit[] unitArray0 = new Unit[2];
      Sergeant sergeant0 = new Sergeant(unitArray0);
      soldierVisitor0.visit(sergeant0);
      assertEquals("sergeant", sergeant0.toString());
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test2()  throws Throwable  {
      SoldierVisitor soldierVisitor0 = new SoldierVisitor();
      Soldier soldier0 = new Soldier((Unit[]) null);
      soldierVisitor0.visit(soldier0);
      assertEquals("soldier", soldier0.toString());
  }
}
