/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 14:07:50 GMT 2024
 */

package com.iluwatar.doubledispatch;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.doubledispatch.FlamingAsteroid;
import com.iluwatar.doubledispatch.GameObject;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

 
public class FlamingAsteroid_ESTest  {


  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      FlamingAsteroid flamingAsteroid0 = new FlamingAsteroid(0, 0, 0, 1);
      // Undeclared exception!
      try { 
        flamingAsteroid0.collision((GameObject) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.iluwatar.doubledispatch.FlamingAsteroid", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      FlamingAsteroid flamingAsteroid0 = new FlamingAsteroid(0, 0, 0, 0);
      flamingAsteroid0.collision(flamingAsteroid0);
      assertTrue(flamingAsteroid0.isOnFire());
  }
}
