/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 13:56:54 GMT 2024
 */

package com.iluwatar.health.check;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.health.check.HealthCheckRepository;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class HealthCheckRepository_ESTest extends HealthCheckRepository_ESTest_scaffolding {
@RegisterExtension
  static EvoRunnerJUnit5 runner = new EvoRunnerJUnit5(HealthCheckRepository_ESTest.class);

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      HealthCheckRepository healthCheckRepository0 = new HealthCheckRepository();
      // Undeclared exception!
      try { 
        healthCheckRepository0.performTestTransaction();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javax/persistence/EntityManager
         //
         verifyException("com.iluwatar.health.check.HealthCheckRepository", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      HealthCheckRepository healthCheckRepository0 = new HealthCheckRepository();
      // Undeclared exception!
      try { 
        healthCheckRepository0.checkHealth();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javax/persistence/EntityManager
         //
         verifyException("com.iluwatar.health.check.HealthCheckRepository", e);
      }
  }
}
