/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 14:09:48 GMT 2024
 */

package com.iluwatar.aggregator.microservices;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.aggregator.microservices.Aggregator;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

 
public class Aggregator_ESTest  {


  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      Aggregator aggregator0 = new Aggregator();
      // Undeclared exception!
      try { 
        aggregator0.getProduct();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.iluwatar.aggregator.microservices.Aggregator", e);
      }
  }
}
