/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 15:21:17 GMT 2024
 */

package com.iluwatar.inventory.microservice;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import com.iluwatar.inventory.microservice.InventoryController;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

 
public class InventoryController_ESTest  {


  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      InventoryController inventoryController0 = new InventoryController();
      int int0 = inventoryController0.getProductInventories();
      assertEquals(5, int0);
  }
}
