/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 14:26:54 GMT 2024
 */

package com.iluwatar.privateclassdata;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import com.iluwatar.privateclassdata.Stew;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

 
public class Stew_ESTest  {


  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      Stew stew0 = new Stew(0, 0, 0, (-2383));
      stew0.taste();
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      Stew stew0 = new Stew((-735), 2725, 2725, (-735));
      stew0.taste();
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test2()  throws Throwable  {
      Stew stew0 = new Stew(0, (-1739), 4061, (-1739));
      stew0.taste();
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test3()  throws Throwable  {
      Stew stew0 = new Stew(315, 315, 315, 315);
      stew0.taste();
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test4()  throws Throwable  {
      Stew stew0 = new Stew(0, 0, (-494), 4);
      stew0.taste();
      stew0.taste();
      stew0.taste();
      stew0.taste();
      stew0.taste();
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test5()  throws Throwable  {
      Stew stew0 = new Stew(0, 0, 0, 0);
      stew0.mix();
  }
}
