/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 16:26:19 GMT 2024
 */

package com.iluwatar.featuretoggle.pattern.propertiesversion;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.featuretoggle.pattern.propertiesversion.PropertiesFeatureToggleVersion;
import java.util.Properties;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class PropertiesFeatureToggleVersion_ESTest extends PropertiesFeatureToggleVersion_ESTest_scaffolding {
@RegisterExtension
  static EvoRunnerJUnit5 runner = new EvoRunnerJUnit5(PropertiesFeatureToggleVersion_ESTest.class);

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      PropertiesFeatureToggleVersion propertiesFeatureToggleVersion0 = null;
      try {
        propertiesFeatureToggleVersion0 = new PropertiesFeatureToggleVersion((Properties) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No Properties Provided.
         //
         verifyException("com.iluwatar.featuretoggle.pattern.propertiesversion.PropertiesFeatureToggleVersion", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      Properties properties0 = new Properties();
      PropertiesFeatureToggleVersion propertiesFeatureToggleVersion0 = null;
      try {
        propertiesFeatureToggleVersion0 = new PropertiesFeatureToggleVersion(properties0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid Enhancement Settings Provided.
         //
         verifyException("com.iluwatar.featuretoggle.pattern.propertiesversion.PropertiesFeatureToggleVersion", e);
      }
  }
}
