/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 14:36:26 GMT 2024
 */

package com.iluwatar.flux.action;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import com.iluwatar.flux.action.MenuItem;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

 
public class MenuItem_ESTest  {


  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      MenuItem[] menuItemArray0 = MenuItem.values();
      assertEquals(3, menuItemArray0.length);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      MenuItem menuItem0 = MenuItem.valueOf("PRODUCTS");
      assertEquals(MenuItem.PRODUCTS, menuItem0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test2()  throws Throwable  {
      MenuItem menuItem0 = MenuItem.COMPANY;
      String string0 = menuItem0.toString();
      assertEquals("Company", string0);
  }
}
