/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 14:39:51 GMT 2024
 */

package com.iluwatar.contect.object;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import com.iluwatar.context.object.ServiceContext;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

 
public class ServiceContext_ESTest  {


  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      ServiceContext serviceContext0 = new ServiceContext();
      serviceContext0.sessionService = "com.iluwatar.context.object.ServiceContext";
      String string0 = serviceContext0.getSessionService();
      assertEquals("com.iluwatar.context.object.ServiceContext", string0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      ServiceContext serviceContext0 = new ServiceContext();
      serviceContext0.setSessionService("");
      String string0 = serviceContext0.getSessionService();
      assertEquals("", string0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test2()  throws Throwable  {
      ServiceContext serviceContext0 = new ServiceContext();
      serviceContext0.searchService = "4u+ZFZtB`D$,w15O$g";
      String string0 = serviceContext0.getSearchService();
      assertEquals("4u+ZFZtB`D$,w15O$g", string0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test3()  throws Throwable  {
      ServiceContext serviceContext0 = new ServiceContext();
      serviceContext0.setSearchService("");
      String string0 = serviceContext0.getSearchService();
      assertEquals("", string0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test4()  throws Throwable  {
      ServiceContext serviceContext0 = new ServiceContext();
      serviceContext0.accountService = "";
      serviceContext0.accountService = "*3D4}k8?,.wuKRhc";
      String string0 = serviceContext0.getAccountService();
      assertEquals("*3D4}k8?,.wuKRhc", string0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test5()  throws Throwable  {
      ServiceContext serviceContext0 = new ServiceContext();
      serviceContext0.setAccountService("");
      String string0 = serviceContext0.getAccountService();
      assertEquals("", string0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test6()  throws Throwable  {
      ServiceContext serviceContext0 = new ServiceContext();
      String string0 = serviceContext0.getSessionService();
      assertNull(string0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test7()  throws Throwable  {
      ServiceContext serviceContext0 = new ServiceContext();
      String string0 = serviceContext0.getAccountService();
      assertNull(string0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test8()  throws Throwable  {
      ServiceContext serviceContext0 = new ServiceContext();
      String string0 = serviceContext0.getSearchService();
      assertNull(string0);
  }
}
