/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 14:05:22 GMT 2024
 */

package com.iluwatar.eda.framework;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.eda.event.UserUpdatedEvent;
import com.iluwatar.eda.framework.EventDispatcher;
import com.iluwatar.eda.framework.Handler;
import com.iluwatar.eda.handler.UserUpdatedEventHandler;
import com.iluwatar.eda.model.User;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

 
public class EventDispatcher_ESTest  {


  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      EventDispatcher eventDispatcher0 = new EventDispatcher();
      UserUpdatedEvent userUpdatedEvent0 = new UserUpdatedEvent((User) null);
      Class<UserUpdatedEvent> class0 = UserUpdatedEvent.class;
      UserUpdatedEventHandler userUpdatedEventHandler0 = new UserUpdatedEventHandler();
      eventDispatcher0.registerHandler(class0, (Handler<UserUpdatedEvent>) userUpdatedEventHandler0);
      // Undeclared exception!
      try { 
        eventDispatcher0.dispatch(userUpdatedEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.iluwatar.eda.handler.UserUpdatedEventHandler", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      EventDispatcher eventDispatcher0 = new EventDispatcher();
      UserUpdatedEvent userUpdatedEvent0 = new UserUpdatedEvent((User) null);
      eventDispatcher0.dispatch(userUpdatedEvent0);
  }
}
