/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 15:30:51 GMT 2024
 */

package com.iluwatar.composite;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import com.iluwatar.composite.LetterComposite;
import com.iluwatar.composite.Messenger;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

 
public class Messenger_ESTest  {


  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      Messenger messenger0 = new Messenger();
      LetterComposite letterComposite0 = messenger0.messageFromElves();
      assertEquals(6, letterComposite0.count());
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      Messenger messenger0 = new Messenger();
      LetterComposite letterComposite0 = messenger0.messageFromOrcs();
      assertEquals(9, letterComposite0.count());
  }
}
