/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 13:28:22 GMT 2024
 */

package com.iluwatar.flux.store;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.flux.action.Action;
import com.iluwatar.flux.action.Content;
import com.iluwatar.flux.action.ContentAction;
import com.iluwatar.flux.action.MenuAction;
import com.iluwatar.flux.action.MenuItem;
import com.iluwatar.flux.store.ContentStore;
import com.iluwatar.flux.view.MenuView;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

 
public class ContentStore_ESTest  {


  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      ContentStore contentStore0 = new ContentStore();
      // Undeclared exception!
      try { 
        contentStore0.onAction((Action) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.iluwatar.flux.store.ContentStore", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      ContentStore contentStore0 = new ContentStore();
      MenuView menuView0 = new MenuView();
      contentStore0.registerView(menuView0);
      Content content0 = Content.PRODUCTS;
      ContentAction contentAction0 = new ContentAction(content0);
      // Undeclared exception!
      try { 
        contentStore0.onAction(contentAction0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class com.iluwatar.flux.store.ContentStore cannot be cast to class com.iluwatar.flux.store.MenuStore (com.iluwatar.flux.store.ContentStore and com.iluwatar.flux.store.MenuStore are in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @1e36d268)
         //
         verifyException("com.iluwatar.flux.view.MenuView", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test2()  throws Throwable  {
      ContentStore contentStore0 = new ContentStore();
      ContentAction contentAction0 = new ContentAction((Content) null);
      contentStore0.onAction(contentAction0);
      contentStore0.getContent();
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test3()  throws Throwable  {
      ContentStore contentStore0 = new ContentStore();
      MenuItem menuItem0 = MenuItem.HOME;
      MenuAction menuAction0 = new MenuAction(menuItem0);
      contentStore0.onAction(menuAction0);
      assertEquals(Content.PRODUCTS, contentStore0.getContent());
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test4()  throws Throwable  {
      ContentStore contentStore0 = new ContentStore();
      Content content0 = contentStore0.getContent();
      assertEquals("Products - This page lists the company's products.", content0.toString());
  }
}
