/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 15:33:15 GMT 2024
 */

package com.iluwatar.flux.store;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.flux.action.Action;
import com.iluwatar.flux.action.ActionType;
import com.iluwatar.flux.action.Content;
import com.iluwatar.flux.action.ContentAction;
import com.iluwatar.flux.action.MenuAction;
import com.iluwatar.flux.action.MenuItem;
import com.iluwatar.flux.store.MenuStore;
import com.iluwatar.flux.view.ContentView;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

 
public class MenuStore_ESTest  {


  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      MenuStore menuStore0 = new MenuStore();
      // Undeclared exception!
      try { 
        menuStore0.onAction((Action) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.iluwatar.flux.store.MenuStore", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      MenuStore menuStore0 = new MenuStore();
      MenuItem menuItem0 = MenuItem.PRODUCTS;
      ContentView contentView0 = new ContentView();
      menuStore0.registerView(contentView0);
      MenuAction menuAction0 = new MenuAction(menuItem0);
      // Undeclared exception!
      try { 
        menuStore0.onAction(menuAction0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class com.iluwatar.flux.store.MenuStore cannot be cast to class com.iluwatar.flux.store.ContentStore (com.iluwatar.flux.store.MenuStore and com.iluwatar.flux.store.ContentStore are in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @7e9a65bb)
         //
         verifyException("com.iluwatar.flux.view.ContentView", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test2()  throws Throwable  {
      MenuStore menuStore0 = new MenuStore();
      MenuItem menuItem0 = MenuItem.COMPANY;
      MenuAction menuAction0 = new MenuAction(menuItem0);
      menuStore0.onAction(menuAction0);
      assertEquals(ActionType.MENU_ITEM_SELECTED, menuAction0.getType());
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test3()  throws Throwable  {
      MenuStore menuStore0 = new MenuStore();
      Content content0 = Content.PRODUCTS;
      ContentAction contentAction0 = new ContentAction(content0);
      menuStore0.onAction(contentAction0);
      assertEquals(MenuItem.HOME, menuStore0.getSelected());
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test4()  throws Throwable  {
      MenuStore menuStore0 = new MenuStore();
      MenuItem menuItem0 = menuStore0.getSelected();
      assertEquals("Home", menuItem0.toString());
  }
}
