/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 13:30:06 GMT 2024
 */

package com.iluwatar.proxy;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.proxy.IvoryTower;
import com.iluwatar.proxy.Wizard;
import com.iluwatar.proxy.WizardTower;
import com.iluwatar.proxy.WizardTowerProxy;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class WizardTowerProxy_ESTest extends WizardTowerProxy_ESTest_scaffolding {
@RegisterExtension
  static EvoRunnerJUnit5 runner = new EvoRunnerJUnit5(WizardTowerProxy_ESTest.class);

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      WizardTowerProxy wizardTowerProxy0 = new WizardTowerProxy((WizardTower) null);
      // Undeclared exception!
      try { 
        wizardTowerProxy0.enter((Wizard) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.iluwatar.proxy.WizardTowerProxy", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      IvoryTower ivoryTower0 = new IvoryTower();
      WizardTowerProxy wizardTowerProxy0 = new WizardTowerProxy(ivoryTower0);
      wizardTowerProxy0.enter((Wizard) null);
      wizardTowerProxy0.enter((Wizard) null);
      wizardTowerProxy0.enter((Wizard) null);
      wizardTowerProxy0.enter((Wizard) null);
  }
}
