/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 15:12:29 GMT 2024
 */

package com.iluwatar.priority.queue;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.priority.queue.Message;
import com.iluwatar.priority.queue.QueueManager;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class QueueManager_ESTest extends QueueManager_ESTest_scaffolding {
@RegisterExtension
  static EvoRunnerJUnit5 runner = new EvoRunnerJUnit5(QueueManager_ESTest.class);

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      QueueManager queueManager0 = new QueueManager(697);
      // Undeclared exception!
      try { 
        queueManager0.publishMessage((Message) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.iluwatar.priority.queue.PriorityMessageQueue", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      QueueManager queueManager0 = null;
      try {
        queueManager0 = new QueueManager((-985));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -985
         //
         verifyException("com.iluwatar.priority.queue.QueueManager", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test2()  throws Throwable  {
      QueueManager queueManager0 = new QueueManager(697);
      Message message0 = queueManager0.receiveMessage();
      assertNull(message0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test3()  throws Throwable  {
      QueueManager queueManager0 = new QueueManager(697);
      Message message0 = new Message("s ar+%d'~L", 1282);
      queueManager0.publishMessage(message0);
      Message message1 = queueManager0.receiveMessage();
      assertEquals("Message{message='s ar+%d'~L', priority=1282}", message1.toString());
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test4()  throws Throwable  {
      QueueManager queueManager0 = new QueueManager(0);
      Message message0 = new Message(":I", 0);
      // Undeclared exception!
      try { 
        queueManager0.publishMessage(message0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("com.iluwatar.priority.queue.PriorityMessageQueue", e);
      }
  }
}
