/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 13:59:33 GMT 2024
 */

package com.iluwatar.intercepting.filter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.intercepting.filter.Target;
import java.awt.HeadlessException;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

 
import org.junit.jupiter.api.Disabled;
public class Target_ESTest  {


  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  @Disabled
    public void test0()  throws Throwable  {
      Target target0 = null;
      try {
        target0 = new Target();
        fail("Expecting exception: HeadlessException");
      
      } catch(HeadlessException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.awt.GraphicsEnvironment", e);
      }
  }
}
