/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 17:07:22 GMT 2024
 */

package com.iluwatar.roleobject;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.roleobject.BorrowerRole;
import com.iluwatar.roleobject.CustomerCore;
import com.iluwatar.roleobject.Role;
import java.util.Optional;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class CustomerCore_ESTest extends CustomerCore_ESTest_scaffolding {
@RegisterExtension
  static EvoRunnerJUnit5 runner = new EvoRunnerJUnit5(CustomerCore_ESTest.class);

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      CustomerCore customerCore0 = new CustomerCore();
      Role role0 = Role.Borrower;
      boolean boolean0 = customerCore0.addRole(role0);
      assertTrue(boolean0);
      
      boolean boolean1 = customerCore0.remRole(role0);
      assertTrue(boolean1 == boolean0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      CustomerCore customerCore0 = new CustomerCore();
      Role role0 = Role.Borrower;
      // Undeclared exception!
      try { 
        customerCore0.getRole(role0, (Class<CustomerCore>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test2()  throws Throwable  {
      BorrowerRole borrowerRole0 = new BorrowerRole();
      // Undeclared exception!
      try { 
        borrowerRole0.addRole((Role) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.iluwatar.roleobject.CustomerCore", e);
      }
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test3()  throws Throwable  {
      CustomerCore customerCore0 = new CustomerCore();
      Role role0 = Role.Borrower;
      boolean boolean0 = customerCore0.hasRole(role0);
      assertFalse(boolean0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test4()  throws Throwable  {
      CustomerCore customerCore0 = new CustomerCore();
      Role role0 = Role.Borrower;
      Class<CustomerCore> class0 = CustomerCore.class;
      Optional<CustomerCore> optional0 = customerCore0.getRole(role0, class0);
      assertNotNull(optional0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test5()  throws Throwable  {
      CustomerCore customerCore0 = new CustomerCore();
      Role role0 = Role.Borrower;
      boolean boolean0 = customerCore0.addRole(role0);
      boolean boolean1 = customerCore0.hasRole(role0);
      assertTrue(boolean1 == boolean0);
      assertTrue(boolean1);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test6()  throws Throwable  {
      CustomerCore customerCore0 = new CustomerCore();
      Role role0 = Role.Borrower;
      boolean boolean0 = customerCore0.remRole(role0);
      assertFalse(boolean0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test7()  throws Throwable  {
      CustomerCore customerCore0 = new CustomerCore();
      String string0 = customerCore0.toString();
      assertEquals("Customer{roles=[]}", string0);
  }
}
