/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 15:04:50 GMT 2024
 */

package com.iluwatar.templatemethod;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import com.iluwatar.templatemethod.SubtleMethod;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

 
public class SubtleMethod_ESTest  {


  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      SubtleMethod subtleMethod0 = new SubtleMethod();
      subtleMethod0.stealTheItem("com.iluwatar.templatemethod.SubtleMethod");
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      SubtleMethod subtleMethod0 = new SubtleMethod();
      subtleMethod0.confuseTarget("com.iluwatar.templatemethod.SubtleMethod");
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test2()  throws Throwable  {
      SubtleMethod subtleMethod0 = new SubtleMethod();
      subtleMethod0.steal();
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test3()  throws Throwable  {
      SubtleMethod subtleMethod0 = new SubtleMethod();
      String string0 = subtleMethod0.pickTarget();
      assertEquals("shop keeper", string0);
  }
}
