/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 16:51:02 GMT 2024
 */

package com.iluwatar.specification.selector;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.specification.creature.Creature;
import com.iluwatar.specification.creature.Shark;
import com.iluwatar.specification.creature.Troll;
import com.iluwatar.specification.property.Color;
import com.iluwatar.specification.property.Mass;
import com.iluwatar.specification.selector.ColorSelector;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ColorSelector_ESTest extends ColorSelector_ESTest_scaffolding {
@RegisterExtension
  static EvoRunnerJUnit5 runner = new EvoRunnerJUnit5(ColorSelector_ESTest.class);

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      Color color0 = Color.DARK;
      ColorSelector colorSelector0 = new ColorSelector(color0);
      Troll troll0 = new Troll();
      boolean boolean0 = colorSelector0.test((Creature) troll0);
      assertTrue(boolean0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      Color color0 = Color.DARK;
      ColorSelector colorSelector0 = new ColorSelector(color0);
      Mass mass0 = new Mass(2174.69345659653);
      Shark shark0 = new Shark(mass0);
      boolean boolean0 = colorSelector0.test((Creature) shark0);
      assertFalse(boolean0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test2()  throws Throwable  {
      Color color0 = Color.GREEN;
      ColorSelector colorSelector0 = new ColorSelector(color0);
      // Undeclared exception!
      try { 
        colorSelector0.test((Creature) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.iluwatar.specification.selector.ColorSelector", e);
      }
  }
}
