/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 15:37:44 GMT 2024
 */

package com.iluwatar.specification.selector;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.specification.creature.Creature;
import com.iluwatar.specification.creature.KillerBee;
import com.iluwatar.specification.creature.Octopus;
import com.iluwatar.specification.property.Mass;
import com.iluwatar.specification.property.Movement;
import com.iluwatar.specification.selector.MovementSelector;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class MovementSelector_ESTest extends MovementSelector_ESTest_scaffolding {
@RegisterExtension
  static EvoRunnerJUnit5 runner = new EvoRunnerJUnit5(MovementSelector_ESTest.class);

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      Movement movement0 = Movement.FLYING;
      MovementSelector movementSelector0 = new MovementSelector(movement0);
      Mass mass0 = new Mass(0.0);
      KillerBee killerBee0 = new KillerBee(mass0);
      boolean boolean0 = movementSelector0.test((Creature) killerBee0);
      assertTrue(boolean0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      Movement movement0 = Movement.FLYING;
      MovementSelector movementSelector0 = new MovementSelector(movement0);
      Mass mass0 = new Mass(0.0);
      Octopus octopus0 = new Octopus(mass0);
      boolean boolean0 = movementSelector0.test((Creature) octopus0);
      assertFalse(boolean0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test2()  throws Throwable  {
      Movement movement0 = Movement.FLYING;
      MovementSelector movementSelector0 = new MovementSelector(movement0);
      // Undeclared exception!
      try { 
        movementSelector0.test((Creature) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.iluwatar.specification.selector.MovementSelector", e);
      }
  }
}
