/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 14:13:20 GMT 2024
 */

package com.iluwatar.stepbuilder;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import com.iluwatar.stepbuilder.CharacterStepBuilder;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class CharacterStepBuilder_ESTest extends CharacterStepBuilder_ESTest_scaffolding {
@RegisterExtension
  static EvoRunnerJUnit5 runner = new EvoRunnerJUnit5(CharacterStepBuilder_ESTest.class);

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      CharacterStepBuilder.NameStep characterStepBuilder_NameStep0 = CharacterStepBuilder.newBuilder();
      assertNotNull(characterStepBuilder_NameStep0);
  }
}
