/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 16 13:53:19 GMT 2024
 */

package com.iluwatar.servicelocator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Timeout;
import java.util.concurrent.TimeUnit;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.servicelocator.Service;
import com.iluwatar.servicelocator.ServiceLocator;
import org.evosuite.runtime.EvoRunnerJUnit5;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.jupiter.api.extension.RegisterExtension;

 
public class ServiceLocator_ESTest  {


  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test0()  throws Throwable  {
      Service service0 = ServiceLocator.getService("jndi/serviceA");
      assertEquals("jndi/serviceA", service0.getName());
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test1()  throws Throwable  {
      Service service0 = ServiceLocator.getService("");
      assertNull(service0);
  }

  @Test
  @Timeout(value = 4000 , unit = TimeUnit.MILLISECONDS)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        ServiceLocator.getService((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.iluwatar.servicelocator.InitContext", e);
      }
  }
}
